//! プレビュー用の固定サンプルリポジトリ。実プロジェクトを開くと「今の作業状態」で
//! 見た目が毎回変わり、プレビューを差分で比べられなくなるため、シーンは必ずこの
//! 合成リポジトリだけを見る (staged / unstaged / untracked / 削除の 4 種が常に揃う)。

use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

// 誤って別のディレクトリを消さないための目印。この名前のファイルが無いディレクトリは
// 作り直しの対象にしない (固定パスを remove_dir_all する以上、この確認は省けない)
const MARKER: &str = ".fv-preview-fixture";

/// $TMPDIR/fv-preview-fixture を作り直して絶対パスを返す
pub fn build() -> Result<PathBuf, Box<dyn Error>> {
    let root = std::env::temp_dir().join("fv-preview-fixture");
    reset_dir(&root)?;
    fs::write(root.join(MARKER), "generated by `fv --preview`\n")?;

    write_initial(&root)?;
    let now = SystemTime::now().duration_since(UNIX_EPOCH)?.as_secs();
    git(&root, &["init", "-q", "-b", "main"])?;
    git(&root, &["add", "-A"])?;
    commit(&root, "feat: TUI コードビューアの骨組み", now - 3 * 86400)?;

    fs::write(root.join("docs/guide.md"), guide_md(true))?;
    git(&root, &["add", "-A"])?;
    commit(&root, "docs: キーバインド一覧を追加", now - 26 * 3600)?;

    fs::write(root.join("src/ui.rs"), ui_rs(true))?;
    git(&root, &["add", "-A"])?;
    commit(
        &root,
        "refactor: ペインの描画を text_pane に一本化",
        now - 2 * 3600,
    )?;

    // ここから先はコミットせず作業ツリーに残す。GIT レーンが 4 種類の状態を
    // 同時に見せられるようにするための仕込み
    fs::write(root.join("src/main.rs"), main_rs(true))?; // unstaged
    fs::write(root.join("src/ui.rs"), ui_rs_staged())?;
    git(&root, &["add", "src/ui.rs"])?; // staged
    fs::remove_file(root.join("docs/old.md"))?; // deleted
    fs::write(root.join("src/new_lane.rs"), NEW_LANE_RS)?; // untracked

    // main.rs::resolve_root と同じく実体パスへ寄せる。macOS の $TMPDIR は
    // /var/... → /private/var/... のシンボリックリンクで、そのまま App へ渡すと
    // git rev-parse --show-toplevel が返す実体パスとツリー走査のパスが食い違い、
    // GIT レーンの絞り込みが 0 件になる (CI の Linux では起きずローカルだけ壊れる)
    Ok(root.canonicalize()?)
}

fn reset_dir(root: &Path) -> Result<(), Box<dyn Error>> {
    if root.exists() {
        if !root.join(MARKER).exists() {
            return Err(format!(
                "{} が fv のプレビュー用ディレクトリではありません (中身を確認してから削除してください)",
                root.display()
            )
            .into());
        }
        fs::remove_dir_all(root)?;
    }
    fs::create_dir_all(root)?;
    Ok(())
}

fn write_initial(root: &Path) -> Result<(), Box<dyn Error>> {
    fs::create_dir_all(root.join("src/app"))?;
    fs::create_dir_all(root.join("docs"))?;
    fs::create_dir_all(root.join("assets"))?;
    fs::write(root.join(".gitignore"), "/target\n*.tmp\n")?;
    // i (無視ファイルの表示) を切り替えたシーン用。既定では走査から落ちるので、
    // 他のシーンの見え方はこれを置いても変わらない
    fs::create_dir_all(root.join("target/debug"))?;
    fs::write(root.join("target/debug/fv"), "(build artifact)\n")?;
    fs::write(
        root.join("target/CACHEDIR.TAG"),
        "Signature: 8a477f597d28d172\n",
    )?;
    fs::write(root.join("scratch.tmp"), "一時メモ\n")?;
    fs::write(root.join("README.md"), README_MD)?;
    fs::write(root.join("src/main.rs"), main_rs(false))?;
    fs::write(root.join("src/ui.rs"), ui_rs(false))?;
    fs::write(root.join("src/app/mod.rs"), APP_MOD_RS)?;
    fs::write(root.join("docs/guide.md"), guide_md(false))?;
    fs::write(root.join("docs/old.md"), "# 旧仕様\n\n削除予定のメモ。\n")?;
    // 子がディレクトリ 1 つだけの階層 (Java の com/example/app のような中継ディレクトリ)
    // が連鎖して開く様子 (tree-chain) 用。docs は他のシーンで展開しないので見え方は変わらない
    fs::create_dir_all(root.join("docs/api/v1"))?;
    fs::write(
        root.join("docs/api/v1/openapi.md"),
        "# API v1\n\n`GET /files` — ツリーの一覧を返す。\n",
    )?;
    // 非テキストの見え方 (VIEW レーンのフォールバック) もプレビューできるようにする
    fs::write(root.join("assets/logo.bin"), [0u8, 1, 2, 255, 254, 0, 42])?;
    Ok(())
}

fn git(root: &Path, args: &[&str]) -> Result<(), Box<dyn Error>> {
    let status = base_command(root).args(args).status()?;
    if !status.success() {
        return Err(format!("git {} に失敗しました", args.join(" ")).into());
    }
    Ok(())
}

// 相対日時 (LOG レーンの一覧・ブランチ一覧) が毎回同じ見え方になるよう、
// 実行時刻からの固定オフセットで author/committer date を打つ
fn commit(root: &Path, message: &str, epoch: u64) -> Result<(), Box<dyn Error>> {
    let date = format!("@{epoch} +0900");
    let status = base_command(root)
        .args(["commit", "-q", "-m", message])
        .env("GIT_AUTHOR_DATE", &date)
        .env("GIT_COMMITTER_DATE", &date)
        .status()?;
    if !status.success() {
        return Err("git commit に失敗しました".into());
    }
    Ok(())
}

// ユーザーの ~/.gitconfig (署名・テンプレート・hook) に左右されないよう、
// 必要な設定は全て -c で明示する
fn base_command(root: &Path) -> Command {
    let mut cmd = Command::new("git");
    cmd.arg("-C")
        .arg(root)
        .args([
            "-c",
            "user.name=fv preview",
            "-c",
            "user.email=preview@example.com",
            "-c",
            "commit.gpgsign=false",
            "-c",
            "core.hooksPath=/dev/null",
        ])
        .env("GIT_OPTIONAL_LOCKS", "0")
        .env("GIT_TERMINAL_PROMPT", "0");
    cmd
}

const README_MD: &str = "\
# sample-app

fv のプレビュー用サンプルリポジトリ。

- `src/` アプリ本体
- `docs/` ドキュメント
- `assets/` バイナリ資産
";

const APP_MOD_RS: &str = "\
use crate::ui;

pub struct App {
    pub title: String,
    pub selected: usize,
    pub items: Vec<String>,
}

impl App {
    pub fn new(title: impl Into<String>) -> Self {
        Self {
            title: title.into(),
            selected: 0,
            items: Vec::new(),
        }
    }

    pub fn select(&mut self, delta: isize) {
        let last = self.items.len().saturating_sub(1) as isize;
        self.selected = (self.selected as isize + delta).clamp(0, last) as usize;
    }

    pub fn render(&self) -> String {
        ui::render(&self.title, &self.items, self.selected)
    }
}
";

const NEW_LANE_RS: &str = "\
//! 追加したばかりでまだ git に登録していないファイル (untracked)

pub struct Lane {
    pub name: &'static str,
}

impl Lane {
    pub fn new(name: &'static str) -> Self {
        Self { name }
    }
}
";

// modified=false が HEAD の内容、true が作業ツリーの内容。
// 行の入れ替え・1 単語だけの変更を混ぜてあり、word-level ハイライト (#29) と
// side-by-side (#30) の見え方をそのままプレビューで確認できる
fn main_rs(modified: bool) -> String {
    let mode = if modified { "Lane::Git" } else { "Lane::View" };
    let extra = if modified {
        "\n    // 起動直後は GIT レーンに入る\n    app.enter_lane(mode);\n"
    } else {
        ""
    };
    format!(
        "mod app;\nmod ui;\n\nuse std::error::Error;\nuse std::path::PathBuf;\n\nuse app::App;\n\nfn main() -> Result<(), Box<dyn Error>> {{\n    let root = std::env::args().nth(1).unwrap_or_else(|| \".\".to_string());\n    let mut app = App::new(\"sample-app\");\n    let mode = {mode};\n    app.items = collect(&PathBuf::from(root))?;\n{extra}    println!(\"{{}}\", app.render());\n    Ok(())\n}}\n\nfn collect(root: &PathBuf) -> Result<Vec<String>, Box<dyn Error>> {{\n    let mut items = Vec::new();\n    for entry in std::fs::read_dir(root)? {{\n        let entry = entry?;\n        items.push(entry.file_name().to_string_lossy().into_owned());\n    }}\n    items.sort();\n    Ok(items)\n}}\n"
    )
}

fn ui_rs(with_gutter: bool) -> String {
    let gutter = if with_gutter {
        "        line.push_str(&format!(\"{:>4} \", i + 1));\n"
    } else {
        ""
    };
    format!(
        "//! 画面の組み立て\n\npub fn render(title: &str, items: &[String], selected: usize) -> String {{\n    let mut out = String::new();\n    out.push_str(title);\n    out.push('\\n');\n    for (i, item) in items.iter().enumerate() {{\n        let mut line = String::new();\n{gutter}        if i == selected {{\n            line.push_str(\"> \");\n        }} else {{\n            line.push_str(\"  \");\n        }}\n        line.push_str(item);\n        out.push_str(&line);\n        out.push('\\n');\n    }}\n    out\n}}\n"
    )
}

// staged だけに入っている変更 (t での基準切替が意味を持つようにするための差分)
fn ui_rs_staged() -> String {
    ui_rs(true).replace("out.push_str(title);", "out.push_str(title.trim());")
}

fn guide_md(with_keys: bool) -> String {
    let keys = if with_keys {
        "\n## キーバインド\n\n| キー | 動作 |\n| --- | --- |\n| `j` / `k` | 上下移動 |\n| `Enter` | 開く |\n| `q` | 終了 |\n"
    } else {
        ""
    };
    format!("# 使い方\n\nsample-app の使い方をまとめる。\n{keys}")
}
